language: php

php:
    - "7.2"
    - "7.3"
    - hhvm
    - nightly

sudo: false

git:
    submodules: false

matrix:
    allow_failures:
        #- php: "7.0"
        #- php: "7.1"
        - php: nightly
        - php: hhvm

before_script:
    - make install

script:
    - make check
    - make test

notifications:
    irc: "irc.freenode.org#dbwebb"
    urls:
      - https://webhooks.gitter.im/e/a3b81c8b3ceb911f69d2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
